### ISSUE TITLE
Does not work with bluetooth keyboard.

### ISSUE THREAD

**Issue by boangs** [machinelevel/sp425-crazy-cow#5]
Does not work with bluetooth keyboard. 
The same bluetooth keyboard works in 'KeyWriter' well.

**Comment by machinelevel** [comment]
Hi there! Thanks for posting this issue. If you have time, please try [**this binary**](https://github.com/machinelevel/sp425-crazy-cow/tree/1-multiple-keyboards/bin) in the branch [1-multiple-keyboards](https://github.com/machinelevel/sp425-crazy-cow/tree/1-multiple-keyboards), to address more complex USB setups.

It may solve the problem simply; I'm using it myself but haven't merged it into the main branch yet, just to avoid disrupting other users.

Let me know if it works for you, and thank you again!

**Comment by boangs** [comment]
Thanks for you reply. It's still not work. I can change the page by using left and right array key of my keybord, but it could not  typing words.
