### ISSUE TITLE
Support Remarkable 2

### ISSUE THREAD

**Issue by b4be1** [machinelevel/sp425-crazy-cow#6]
Hi Eric,

I like the idea of this repository a lot. However, I am not able to connect a Bluetooth keyboard to my Remarkable 2 to experience it. It seems the Bluetooth dongle is not recognized at all by the device. I followed the debug procedure from https://github.com/machinelevel/sp425-crazy-cow/issues/1, but `/dev/input/` only contains the pencil input and touchscreen. Any ideas how to debug this or how to proceed in general?

I haven't tried connecting a normal USB keyboard yet, but I will try it tomorrow.

Best,
Boris

**Comment by machinelevel** [comment]
Hi Boris! Thanks for posting this issue. If you have time, please try this binary in the branch [**1-multiple-keyboards**](https://github.com/machinelevel/sp425-crazy-cow/tree/1-multiple-keyboards/bin), to address more complex USB setups. I've succeeded in using it with Bluetooth, but setups do differ.

Also, if that branch does work on the rM2, please let me know! I've just got my trusty rM1, so it'd be good to have a test case.

It may solve the problem simply; I'm using it myself but haven't merged it into the main branch yet, just to avoid disrupting other users.

Let me know if it works for you, and thank you again!

**Comment by b4be1** [comment]
Hi Eric,

Thanks for your reply and support. The issue turns out to be rm2-specific. Namely, the USB-C port can only be used for charging (at least at the moment). The only option right now is to use the pogo pins next to the USB-C port to connect the Bluetooth dongle. There is more info on this problem available here https://github.com/ddvk/remarkable-hacks/issues/122#issuecomment-730955977.

Best,
Boris

**Comment by isman7** [comment]
Hi all, we have been discussing these connectors a lot here: https://github.com/dps/remarkable-keywriter/issues/14, an actual Bluetooth keyboard worked for me using the pogo pins. As Crazy Cow is easy to run than this app I have tested it tonight, and everything works! 

![rm2-keyboard-crazy-cow](https://user-images.githubusercontent.com/9478220/106532292-363f9f80-64f0-11eb-972b-f25679209554.gif)

So, technically crazy cow works with remarkable 2 out of the box using the master branch, only you have to build some complex connector. 

Edit, detail of the connector: 

![image](https://user-images.githubusercontent.com/9478220/106532513-9b939080-64f0-11eb-91cd-eaab9dd7497d.png)

**Comment by machinelevel** [comment]
Aha that's fantastic! Thanks for this, will add a note to the Readme. Well done!

**Comment by isman7** [comment]
Hey! As @b4be1 asked for USB-C support as USB Host, I can confirm you now it is possible, as you can follow in these thread from remarkable-keywriter: https://github.com/dps/remarkable-keywriter/issues/14#issuecomment-796275021. Cheers, Ismael

**Comment by b4be1** [comment]
@isman7 thanks for sharing the info. With the USB-C, it is much more usable now.

**Comment by CrayCJ** [comment]
I'd like to report the following process to be working form me on the rm2 repeatedly:

- I'm on a rm2, software version 2.14.1.866, with [ddvk's hacks](https://github.com/ddvk/remarkable-hacks); works with and without.
- I use the following adapter: [Digitus DA70893](https://cdn-reichelt.de/bilder/web/xxl_ws/E910/DIGITUS_DA70893_ANW_04.png).
- ([This ](https://es.aliexpress.com/item/1005003478647974.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=60179515843&aff_fcid=43aeaf6ae4f34130908ca81ebd39d43a-1661144449767-06219-_uWpmuj&tt=MG&aff_fsk=_uWpmuj&aff_platform=default&sk=_uWpmuj&aff_trace_key=43aeaf6ae4f34130908ca81ebd39d43a-1661144449767-06219-_uWpmuj&shareId=60179515843&businessType=ProductDetail&platform=AE&terminal_id=046bddf8581b489b86e7569b10d98e7e&afSmartRedirect=y) is reported to work also, by [this ](https://discord.com/channels/385916768696139794/774159226670809118/1010163350568714250) person.)
- And some generic and quite simple keyboard, but [apparently](https://discord.com/channels/385916768696139794/774159226670809118/1010968455488487434) many - or even any? - should work.
- Installed crazy cow as [described in the readme](https://github.com/machinelevel/sp425-crazy-cow#installation-instructions).

This is how I got this to work:
1. SSH to RM2 - the `code lines beneath` are to be typed into your ssh terminal, or are returned by it...
2. Attach usb c power cable - without adapter or anything - to usb c port of rm2 to power it. rm2 charges and shows charging icon.
3. (optional, list usb devices: `lsusb`
--> nothing is returned, as expected.)
4. Change state of usb port (and - optionally - list usb devices):
`echo host > /sys/kernel/debug/ci_hdrc.0/role`
(optional: `lsusb`
return: `Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
--> the rm2's own usb c port is detected.)
5. Detach usb c power cable from rm2. As the state of the port was changed to host, the charging icon on the rm2 will NOT disappear now!!
6. Attach usb c power cable to usb c port of adapter. Attach adapter to usb c port of rm2. (This will charge the rm2 apparently.)
7. (optional, list usb devices: `lsusb`
 return:
`Bus 001 Device 003: ID 0639:7210 Chrontel, Inc. USB 2.0 Hub`
`Bus 001 Device 002: ID 1a40:0801 Terminus Technology Inc. USB 2.0 Hub`
`Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
--> the rm2's own usb c port from previously as well as - at least for me - two aditional port, probably the c and a port of my adapter, are detected!)
8. Attach USB A Keyboard to USB A port of adapter.
9. (optional, list usb devices: `lsusb`
return as in 7, plus above those:
`Bus 001 Device 004: ID 09da:0260 A4Tech Co., Ltd. KV-300H Isolation Keyboard`
--> the keyboard is detected!!
10. Have fun, type, start any typing applications (like crazy cow, which can be kept running though, i.e. [might(!)](https://github.com/machinelevel/sp425-crazy-cow/issues/11) not have to be stopped and re-started each time), etc.
11. When done: `echo gadget > /sys/kernel/debug/ci_hdrc.0/role`
--> This is to revert the rm2's usb c port to it's previous state. Without this, the charging icon won't disappear, but the rm2 seems to draw power regardless of the port's state, if a power cable is attached in any way.
12. Detatch adapter, etc.
13. Attach and detach power to and from rm2 to make the charging icon disappear.
14. Repeat...

@machinelevel Many, many thanks for your marvellous piece of software. This is so useful and even works with the different pens!
