### ISSUE TITLE
Support Multi Device Bluetooth Keyboard

### ISSUE THREAD

**Issue by b4be1** [machinelevel/sp425-crazy-cow#7]
Hi Eric,

I would like to use a [keyboard Jelly Comb B046](https://www.jellycomb.com/products/b046-bluetooth-keyboard) with my Remarkable 2. For that, I need to pair the keyboard with the device. Therefore, I bought a [USB bluetooth dongle TP-Link UB400](https://www.tp-link.com/de/home-networking/adapter/ub400/) and connected it via an OTG USB->USB-C to the tablet. However, there seems to be no bluetooth module installed on the latest Linux version on the Remarkable. Do you have an advice on how to set it up? And would I need to make any changes to Crazy Cow to get it running in this setting?

Best,
Boris

**Comment by machinelevel** [comment]
Hi Boris! Similar to #6, this binary in the branch [**1-multiple-keyboards**](https://github.com/machinelevel/sp425-crazy-cow/tree/1-multiple-keyboards/bin) might help.

One thing top try: with your keyboard connected, do the left and right arrows on the keyboard change the page? If so, that's promising, and reduces the solution search space.

**Comment by b4be1** [comment]
Hi Eric,

The trick with this keyboard is that I need to pair it with the device I want to control. So, it is not a usual USB keyboard that directly fires up once I plug in the USB dongle. Therefore, I plan to compile Bluez as discussed in [remarkable-keywriter with a bluetooth keyboard](https://www.reddit.com/r/RemarkableTablet/comments/e8p22h/remarkablekeywriter_with_a_bluetooth_keyboard/fadjjq9?utm_source=share&utm_medium=web2x&context=3). But first I need to connect a USB port to the pogo pins to have a USB connection to rM2 at all https://github.com/machinelevel/sp425-crazy-cow/issues/6#issuecomment-731709663.

Best,
Boris

**Comment by b4be1** [comment]
So, both https://github.com/machinelevel/sp425-crazy-cow/issues/6 and https://github.com/machinelevel/sp425-crazy-cow/issues/7 are actually issues with the rm2 itself, and are out of scope of Crazy Cow, I would say. Therefore, feel free to close them. If I get it to work, I will post my solution here.

**Comment by b4be1** [comment]
The solution is given in https://github.com/machinelevel/sp425-crazy-cow/issues/6#issuecomment-797095272
