### ISSUE TITLE
Recommend edit to instructions

### ISSUE THREAD

**Issue by dpowyslybbe** [machinelevel/sp425-crazy-cow#8]
Hi, so can I just say this is incredible - such a useful tool! Thank you so much!

It took a while to get it to work, however. I followed the README.md, and whilst the keyboard worked (ie. Arrow keys changed pages) nothing else happened.

To cut a long story short I needed to make crazy-cow executable by typing in "chmod +x crazy-cow" after completing point 2 of the installation instructions. Can I recommend you add this step in?

Thanks again, Dom

**Comment by machinelevel** [comment]
Hi Dom,
Change made. Thanks very much for your note!
